# how to create image using array

In [17]:
import cv2
import numpy as np

In [5]:
image=np.array([
    [
        [255,0,0],[255,0,255],[255,145,5],
    ],
    [
        [255,0,0],[255,0,255],[255,145,5],
    ],
    [
        [255,0,0],[255,0,255],[255,145,5],
    ],
    
])

In [6]:
cv2.imshow("hand made image",image)
cv2.waitKey(1500)
cv2.destroyAllWindows()

In [18]:
flagimage=cv2.imread("flag.png")
flagimage[310][232]=(255,0,0)
flagimage[310][233]=(255,0,0)
flagimage[310][234]=(255,0,0)
flagimage[310][235]=(255,0,0)
cv2.imshow("flag",flagimage)
cv2.waitKey(25000)
cv2.destroyAllWindows()

In [14]:
print(flagimage[310][232])

[255   0   0]


In [5]:
flagimage[310][232]=(255,0,0)

In [20]:
grayimage=cv2.cvtColor(flagimage,cv2.COLOR_BGR2GRAY)
cv2.imshow("GRAY flag",grayimage)
cv2.waitKey(2500)
cv2.destroyAllWindows()

In [21]:
print(grayimage)   #each pixel has only one channel

[[29 29 29 ... 76 76 76]
 [29 29 29 ... 76 76 76]
 [29 29 29 ... 76 76 76]
 ...
 [29 29 29 ... 76 76 76]
 [29 29 29 ... 76 76 76]
 [29 29 29 ... 76 76 76]]


In [22]:
print(flagimage)  #each pixel has three channels

[[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


In [23]:
#you can save image shape by this method because it return list
row,col,channel=flagimage.shape

In [31]:
print(row , ",",col,",",channel)

350 , 600 , 3


In [32]:
print(flagimage.shape)

(350, 600, 3)


In [35]:
#you can save a specific part of image by using this method simply

cutimage=grayimage[100:200,200:400]
cv2.imshow("cut image",cutimage)
cv2.waitKey(25000)
cv2.destroyAllWindows()

In [36]:
#you can also save cut BGR image 
cutimage=flagimage[100:200,200:400]
cv2.imshow("cut image",cutimage)
cv2.waitKey(25000)
cv2.destroyAllWindows()